# Generated by Django 2.2 on 2026-01-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrayReleaseRecord',
            fields=[
                ('ID', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(help_text='租户ID', max_length=32)),
                ('region_name', models.CharField(help_text='数据中心', max_length=64)),
                ('app_id', models.IntegerField(help_text='应用ID')),
                ('app_name', models.CharField(help_text='应用名称', max_length=128)),
                ('template_id', models.CharField(help_text='模板ID (group_key)', max_length=128)),
                ('template_name', models.CharField(help_text='模板名称', max_length=255)),
                ('template_version', models.CharField(help_text='模板版本', max_length=64)),
                ('original_upgrade_group_id', models.IntegerField(help_text='原始服务组ID')),
                ('gray_upgrade_group_id', models.IntegerField(help_text='灰度服务组ID')),
                ('original_service_id', models.CharField(help_text='原始服务ID', max_length=32)),
                ('original_service_cname', models.CharField(help_text='原始服务名称', max_length=100)),
                ('gray_service_id', models.CharField(help_text='灰度服务ID', max_length=32)),
                ('gray_service_cname', models.CharField(help_text='灰度服务名称', max_length=100)),
                ('service_mappings', models.TextField(help_text='服务映射关系（JSON格式）')),
                ('domain_name', models.CharField(help_text='域名', max_length=255)),
                ('gray_ratio', models.IntegerField(default=0, help_text='灰度比例 0-100')),
                ('status', models.CharField(default='active', help_text='状态: active-灰度中, completed-已完成, cancelled-已取消', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'db_table': 'gray_release_record',
            },
        ),
        migrations.AddIndex(
            model_name='grayreleaserecord',
            index=models.Index(fields=['tenant_id', 'app_id'], name='gray_releas_tenant__b06ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='grayreleaserecord',
            index=models.Index(fields=['tenant_id', 'status'], name='gray_releas_tenant__9439d8_idx'),
        ),
    ]
