# Generated by Django 2.2 on 2026-03-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_platformfeatureflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamHelmReleaseSource',
            fields=[
                ('ID', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('team_name', models.CharField(help_text='团队名称', max_length=64)),
                ('region_name', models.CharField(help_text='集群名称', max_length=64)),
                ('namespace', models.CharField(help_text='命名空间', max_length=128)),
                ('release_name', models.CharField(help_text='helm release 名称', max_length=128)),
                ('source_type', models.CharField(help_text='安装来源类型', max_length=32)),
                ('repo_name', models.CharField(blank=True, default='', help_text='仓库名称', max_length=128, null=True)),
                ('repo_url', models.CharField(blank=True, default='', help_text='仓库地址', max_length=255, null=True)),
                ('chart_name', models.CharField(blank=True, default='', help_text='chart 名称', max_length=128, null=True)),
                ('chart_version', models.CharField(blank=True, default='', help_text='chart 版本', max_length=64, null=True)),
                ('creator', models.CharField(blank=True, default='', help_text='操作人', max_length=64, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True)),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
            ],
            options={
                'db_table': 'team_helm_release_source',
                'unique_together': {('region_name', 'namespace', 'release_name')},
            },
        ),
    ]
