# Generated by Django 2.2 on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_teamhelmreleasesource_values_yaml'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubeBlocksBackupRepo',
            fields=[
                ('ID', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(help_text='团队ID', max_length=32)),
                ('team_name', models.CharField(help_text='团队名称', max_length=64)),
                ('region_name', models.CharField(help_text='数据中心名称', max_length=64)),
                ('namespace', models.CharField(help_text='团队命名空间', max_length=64)),
                ('display_name', models.CharField(help_text='显示名称', max_length=64)),
                ('repo_name', models.CharField(help_text='KubeBlocks BackupRepo 名称', max_length=128)),
                ('secret_name', models.CharField(help_text='凭据 Secret 名称', max_length=128)),
                ('secret_namespace', models.CharField(default='rbd-plugins', help_text='凭据 Secret 命名空间', max_length=64)),
                ('storage_provider', models.CharField(default='s3', help_text='StorageProvider 名称', max_length=32)),
                ('access_method', models.CharField(default='Tool', help_text='访问方式', max_length=16)),
                ('bucket', models.CharField(help_text='S3 Bucket', max_length=255)),
                ('endpoint', models.CharField(help_text='S3 Endpoint', max_length=255)),
                ('region', models.CharField(blank=True, default='', help_text='S3 Region', max_length=64, null=True)),
                ('volume_capacity', models.CharField(default='100Gi', help_text='BackupRepo 容量', max_length=32)),
                ('pv_reclaim_policy', models.CharField(default='Retain', help_text='PV 回收策略', max_length=16)),
                ('path_prefix', models.CharField(blank=True, default='', help_text='备份路径前缀', max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='', help_text='状态', max_length=32, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除')),
                ('creator', models.CharField(blank=True, default='', help_text='创建人', max_length=64, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True)),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
            ],
            options={
                'db_table': 'kubeblocks_backup_repo',
                'unique_together': {('region_name', 'repo_name'), ('tenant_id', 'region_name', 'display_name', 'is_deleted')},
            },
        ),
    ]
