# Generated by Django 2.2 on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_kubeblocksbackuprepo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubeblocksbackuprepo',
            name='force_path_style',
            field=models.BooleanField(default=True, help_text='是否使用路径风格访问 Bucket'),
        ),
    ]
