# Generated by Django 5.2 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0007_kubeblocksbackuprepo_force_path_style"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPDeviceAuthorization",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_code_hash", models.CharField(max_length=64, unique=True)),
                ("user_code_hash", models.CharField(max_length=64, unique=True)),
                ("client_id", models.CharField(max_length=64)),
                ("client_name", models.CharField(max_length=128)),
                ("scope", models.CharField(default="mcp", max_length=64)),
                ("status", models.CharField(
                    choices=[
                        ("pending", "pending"),
                        ("approved", "approved"),
                        ("denied", "denied"),
                        ("consumed", "consumed"),
                        ("expired", "expired"),
                    ],
                    default="pending",
                    max_length=16,
                )),
                ("approving_user_id", models.IntegerField(blank=True, null=True)),
                ("enterprise_id", models.CharField(blank=True, default="", max_length=64)),
                ("polling_interval", models.PositiveSmallIntegerField(default=5)),
                ("failed_inspection_attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("denied_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "mcp_device_authorization",
                "indexes": [models.Index(fields=["status", "expires_at"], name="mcp_device_status_exp_idx")],
            },
        ),
        migrations.CreateModel(
            name="MCPDeviceAuthorizationRateLimit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bucket_hash", models.CharField(max_length=64, unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
                ("window_started_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mcp_device_authorization_rate_limit",
            },
        ),
    ]
