# Generated by Django 5.2 on 2026-08-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0008_mcp_device_authorization"),
    ]
    operations = [
        migrations.CreateModel(
            name="RainSkillsSkillSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("enterprise_id", models.CharField(max_length=64)),
                ("skill_id", models.CharField(max_length=128)),
                ("profile", models.CharField(max_length=16)),
                ("package_version", models.CharField(max_length=64)),
                ("source_revision", models.CharField(blank=True, max_length=128, null=True)),
                ("content_sha256", models.CharField(max_length=64)),
                ("bundle_sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("content_text", models.TextField()),
                ("provenance", models.CharField(default="client_manifest_verified", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rainskills_skill_snapshot",
            },
        ),
        migrations.CreateModel(
            name="RainSkillsOperation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("operation_id", models.CharField(max_length=64)),
                ("enterprise_id", models.CharField(max_length=64)),
                ("user_id", models.CharField(max_length=64)),
                ("username", models.CharField(blank=True, max_length=128, null=True)),
                ("deploy_client", models.CharField(max_length=32)),
                ("skill_id", models.CharField(blank=True, max_length=128, null=True)),
                ("root_skill_id", models.CharField(blank=True, max_length=128, null=True)),
                ("tool_name", models.CharField(max_length=128)),
                ("operation_class", models.CharField(max_length=16)),
                ("risk", models.CharField(max_length=16)),
                ("scope", models.CharField(max_length=16)),
                ("arguments_digest", models.CharField(max_length=64)),
                ("input_json", models.JSONField(blank=True, null=True)),
                ("target_context", models.JSONField(blank=True, null=True)),
                ("confirmation_type", models.CharField(max_length=32)),
                ("status", models.CharField(default="executing", max_length=32)),
                ("output_summary", models.TextField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("skill_snapshot", models.ForeignKey(
                    blank=True,
                    db_column="skill_snapshot_id",
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="operations",
                    to="console.rainskillsskillsnapshot",
                )),
            ],
            options={
                "db_table": "rainskills_operation",
                "indexes": [
                    models.Index(fields=["enterprise_id", "status", "started_at"], name="rs_op_status_started_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RainSkillsOperationEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_id", models.CharField(max_length=128, unique=True)),
                ("enterprise_id", models.CharField(max_length=64)),
                ("operation_id", models.CharField(max_length=64)),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rainskills_operation_event",
                "indexes": [
                    models.Index(fields=["enterprise_id", "id"], name="rs_event_enterprise_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="rainskillsskillsnapshot",
            constraint=models.UniqueConstraint(
                fields=("enterprise_id", "skill_id", "profile", "content_sha256"),
                name="uk_rs_snapshot_enterprise_skill_digest",
            ),
        ),
        migrations.AddConstraint(
            model_name="rainskillsoperation",
            constraint=models.UniqueConstraint(
                fields=("enterprise_id", "operation_id"),
                name="uk_rs_operation_enterprise_id",
            ),
        ),
    ]
