# Generated by Django 5.2 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0009_rainskills_operation_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="k8sresource",
            name="delete_status",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="k8sresource",
            name="delete_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="k8sresource",
            name="delete_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="k8sresource",
            name="delete_generation",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="k8sresource",
            name="region_resource_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="k8sresource",
            index=models.Index(fields=["app_id", "delete_status"], name="k8s_res_app_delete_idx"),
        ),
    ]
