{{- if .Values.console.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.console.fullname }}
  labels:
    rainbond: console
spec:
  replicas: {{ .Values.console.replicasCount }}
  selector:
  {{- with .Values.console.selectorLabels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  template:
    metadata:
    {{- with .Values.console.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.console.selectorLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      containers:
        - name: console
          image: "{{ .Values.console.image.repository }}:{{ .Values.console.image.tag }}"
          imagePullPolicy: {{ .Values.console.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: rainbond-mysql-secret
            - secretRef:
                name: rainbond-redis-secret
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: REGION_CONNECTION_TIMEOUT
              value: "2.0"
            - name: REGION_RED_TIMEOUT
              value: "5.0"
            - name: RELEASE_DESC
              value: "{{ .Values.console.RELEASE_DESC }}"
            - name: DB_TYPE
              value: mysql
            - name: MYSQL_HOST
              value: "{{ .Values.mysql.fullname }}"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_PASS
              value: "$(MYSQL_PASSWORD)"
            - name: REDIS_HOST
              value: "{{ .Values.redis.fullname }}"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASS
              value: "$(REDISC_REQUIREPASS)"
            - name: ADAPTOR_HOST
              value: "{{ .Values.adaptor.fullname }}"
            - name: ADAPTOR_PORT
              value: "8080"
            - name: PORT
              value: "5000"
          ports:
            - name: tcp
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /console/config/info
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 20
          volumeMounts:
          - mountPath: /app/data
            name: console-data
          - mountPath: /app/logs
            name: console-logs
          resources:
            {{- toYaml .Values.console.resources | nindent 12 }}
      volumes:
      - name: console-data
        persistentVolumeClaim:
          claimName: rainbond-console-pvc-data
      - name: console-logs
        persistentVolumeClaim:
          claimName: rainbond-console-pvc-logs
      {{- with .Values.console.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.console.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}