# -*- coding: utf-8 -*-
from django.conf.urls import url

from console.views.team_resources import (
    NsResourceTypesView,
    NsResourcesView,
    NsResourceDetailView,
    HelmReleasesView,
    HelmChartPreviewView,
    HelmReleaseDetailView,
    HelmReleaseHistoryView,
    HelmReleaseRollbackView,
    ResourceCenterWorkloadDetailView,
    ResourceCenterPodDetailView,
    ResourceCenterEventsView,
    ResourceCenterPodLogsView,
    ResourceCenterWSInfoView,
)

urlpatterns = [
    url(r'^teams/(?P<team_name>[^/]+)/regions/(?P<region_name>[^/]+)/ns-resource-types$',
        NsResourceTypesView.as_view()),
    url(r'^teams/(?P<team_name>[^/]+)/regions/(?P<region_name>[^/]+)/ns-resources$',
        NsResourcesView.as_view()),
    url(r'^teams/(?P<team_name>[^/]+)/regions/(?P<region_name>[^/]+)/ns-resources/(?P<name>[^/]+)$',
        NsResourceDetailView.as_view()),
    url(r'^teams/(?P<team_name>[^/]+)/regions/(?P<region_name>[^/]+)/helm/releases$',
        HelmReleasesView.as_view()),
    url(r'^teams/(?P<team_name>[^/]+)/regions/(?P<region_name>[^/]+)/helm/chart-preview$',
        HelmChartPreviewView.as_view()),
    url(r'^teams/(?P<team_name>[^/]+)/regions/(?P<region_name>[^/]+)/helm/releases/(?P<release_name>[^/]+)$',
        HelmReleaseDetailView.as_view()),
    url(r'^teams/(?P<team_name>[^/]+)/regions/(?P<region_name>[^/]+)/helm/releases/(?P<release_name>[^/]+)/history$',
        HelmReleaseHistoryView.as_view()),
    url(r'^teams/(?P<team_name>[^/]+)/regions/(?P<region_name>[^/]+)/helm/releases/(?P<release_name>[^/]+)/rollback$',
        HelmReleaseRollbackView.as_view()),
    url(r'^teams/(?P<team_name>[^/]+)/regions/(?P<region_name>[^/]+)/resource-center/workloads/(?P<resource>[^/]+)/(?P<name>[^/]+)$',
        ResourceCenterWorkloadDetailView.as_view()),
    url(r'^teams/(?P<team_name>[^/]+)/regions/(?P<region_name>[^/]+)/resource-center/pods/(?P<pod_name>[^/]+)$',
        ResourceCenterPodDetailView.as_view()),
    url(r'^teams/(?P<team_name>[^/]+)/regions/(?P<region_name>[^/]+)/resource-center/events$',
        ResourceCenterEventsView.as_view()),
    url(r'^teams/(?P<team_name>[^/]+)/regions/(?P<region_name>[^/]+)/resource-center/pods/(?P<pod_name>[^/]+)/logs$',
        ResourceCenterPodLogsView.as_view()),
    url(r'^teams/(?P<team_name>[^/]+)/regions/(?P<region_name>[^/]+)/resource-center/ws-info$',
        ResourceCenterWSInfoView.as_view()),
]
